name: firstpipeline

on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  build_pana_poren:
    runs-on: ubuntu-latest

    steps:
     - name:  checkout to runner
       uses: actions/checkout@v4

     - name:  list the files
       run: ls    

    