name: firstpipeline

on:
 workflow_dispatch

jobs:
  build pana poren:
    runs-on: ubuntu-latest

    steps:
     - name:  checkout to runner
        uses: actions/checkout@v4

     - name:  list the files
        run: ls    

    