name: firstpipeline

on:
  push:
    branches:
     - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: lokiii2001/xogame:latest  


jobs:
  build_pana_poren:
    runs-on: ubuntu-latest

    steps:
     - name:  checkout to runner
       uses: actions/checkout@v4

     - name:  Docker login
       uses: docker/login-action@v2
       with:
         username: ${{vars.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}

     - name: Remove old docker image
       run: docker rmi ${{env.DOCKER_IMAGE}} || true     

     - name: build docker image     
       run: docker build -t ${{env.DOCKER_IMAGE}} .

     - name: push docker image
       run: docker push ${{env.DOCKER_IMAGE}}   

  deploy_pana_poren:
    runs-on: ubuntu-latest
    needs: build_pana_poren
    steps:
     - name: AWS EC2 SSH
       uses: appleboy/ssh-action@v0.1.5
       with:
         host: ${{vars.HOST_IP}}
         username: ${{vars.USERNAME}}
         key: ${{secrets.PASSWORD}}
         script: |
          docker pull ${{env.DOCKER_IMAGE}}  
          docker stop xogame || true
          docker rm xogame || true
          docker run -d --name xogame -p 80:80 ${{env.DOCKER_IMAGE}}